export const DEFAULT_THEME = 'Colorway-CatppuccinMocha.ovt';

export const THEMES = [
  { file: 'Colorway-90sAnime.ovt', name: '90s Anime' },
  { file: 'Colorway-AMOLED.ovt', name: 'AMOLED' },
  { file: 'Colorway-AdaptaEvergreen.ovt', name: 'Adapta Evergreen' },
  { file: 'Colorway-Aura.ovt', name: 'Aura' },
  { file: 'Colorway-Ayu.ovt', name: 'Ayu' },
  { file: 'Colorway-Carbonfox.ovt', name: 'Carbonfox' },
  { file: 'Colorway-BerryNebula.ovt', name: 'Berry Nebula' },
  { file: 'Colorway-CatppuccinFrappe-Blue.ovt', name: 'Catppuccin Frappé — Blue' },
  { file: 'Colorway-CatppuccinFrappe-Green.ovt', name: 'Catppuccin Frappé — Green' },
  { file: 'Colorway-CatppuccinFrappe-Lavender.ovt', name: 'Catppuccin Frappé — Lavender' },
  { file: 'Colorway-CatppuccinFrappe-Maroon.ovt', name: 'Catppuccin Frappé — Maroon' },
  { file: 'Colorway-CatppuccinFrappe-Peach.ovt', name: 'Catppuccin Frappé — Peach' },
  { file: 'Colorway-CatppuccinFrappe-Pink.ovt', name: 'Catppuccin Frappé — Pink' },
  { file: 'Colorway-CatppuccinFrappe-Red.ovt', name: 'Catppuccin Frappé — Red' },
  { file: 'Colorway-CatppuccinFrappe-Rosewater.ovt', name: 'Catppuccin Frappé — Rosewater' },
  { file: 'Colorway-CatppuccinFrappe-Teal.ovt', name: 'Catppuccin Frappé — Teal' },
  { file: 'Colorway-CatppuccinFrappe-Yellow.ovt', name: 'Catppuccin Frappé — Yellow' },
  { file: 'Colorway-CatppuccinLatte-Blue.ovt', name: 'Catppuccin Latte — Blue' },
  { file: 'Colorway-CatppuccinLatte-Green.ovt', name: 'Catppuccin Latte — Green' },
  { file: 'Colorway-CatppuccinLatte-Lavender.ovt', name: 'Catppuccin Latte — Lavender' },
  { file: 'Colorway-CatppuccinLatte-Maroon.ovt', name: 'Catppuccin Latte — Maroon' },
  { file: 'Colorway-CatppuccinLatte-Peach.ovt', name: 'Catppuccin Latte — Peach' },
  { file: 'Colorway-CatppuccinLatte-Pink.ovt', name: 'Catppuccin Latte — Pink' },
  { file: 'Colorway-CatppuccinLatte-Red.ovt', name: 'Catppuccin Latte — Red' },
  { file: 'Colorway-CatppuccinLatte-Rosewater.ovt', name: 'Catppuccin Latte — Rosewater' },
  { file: 'Colorway-CatppuccinLatte-Teal.ovt', name: 'Catppuccin Latte — Teal' },
  { file: 'Colorway-CatppuccinLatte-Yellow.ovt', name: 'Catppuccin Latte — Yellow' },
  { file: 'Colorway-CatppuccinMacchiato-Blue.ovt', name: 'Catppuccin Macchiato — Blue' },
  { file: 'Colorway-CatppuccinMacchiato-Green.ovt', name: 'Catppuccin Macchiato — Green' },
  { file: 'Colorway-CatppuccinMacchiato-Lavender.ovt', name: 'Catppuccin Macchiato — Lavender' },
  { file: 'Colorway-CatppuccinMacchiato-Maroon.ovt', name: 'Catppuccin Macchiato — Maroon' },
  { file: 'Colorway-CatppuccinMacchiato-Peach.ovt', name: 'Catppuccin Macchiato — Peach' },
  { file: 'Colorway-CatppuccinMacchiato-Pink.ovt', name: 'Catppuccin Macchiato — Pink' },
  { file: 'Colorway-CatppuccinMacchiato-Red.ovt', name: 'Catppuccin Macchiato — Red' },
  { file: 'Colorway-CatppuccinMacchiato-Rosewater.ovt', name: 'Catppuccin Macchiato — Rosewater' },
  { file: 'Colorway-CatppuccinMacchiato-Teal.ovt', name: 'Catppuccin Macchiato — Teal' },
  { file: 'Colorway-CatppuccinMacchiato-Yellow.ovt', name: 'Catppuccin Macchiato — Yellow' },
  { file: 'Colorway-CatppuccinMocha-Blue.ovt', name: 'Catppuccin Mocha — Blue' },
  { file: 'Colorway-CatppuccinMocha-Green.ovt', name: 'Catppuccin Mocha — Green' },
  { file: 'Colorway-CatppuccinMocha-Lavender.ovt', name: 'Catppuccin Mocha — Lavender' },
  { file: 'Colorway-CatppuccinMocha-Maroon.ovt', name: 'Catppuccin Mocha — Maroon' },
  { file: 'Colorway-CatppuccinMocha-Peach.ovt', name: 'Catppuccin Mocha — Peach' },
  { file: 'Colorway-CatppuccinMocha-Pink.ovt', name: 'Catppuccin Mocha — Pink' },
  { file: 'Colorway-CatppuccinMocha-Red.ovt', name: 'Catppuccin Mocha — Red' },
  { file: 'Colorway-CatppuccinMocha-Rosewater.ovt', name: 'Catppuccin Mocha — Rosewater' },
  { file: 'Colorway-CatppuccinMocha-Teal.ovt', name: 'Catppuccin Mocha — Teal' },
  { file: 'Colorway-CatppuccinMocha-Yellow.ovt', name: 'Catppuccin Mocha — Yellow' },
  { file: 'Colorway-CatppuccinMocha.ovt', name: 'Catppuccin Mocha' },
  { file: 'Colorway-CaveOfThePast.ovt', name: 'Cave of the Past' },
  { file: 'Colorway-ClaudeCode.ovt', name: 'Claude Code' },
  { file: 'Colorway-ClaudeCodeWarm.ovt', name: 'Claude Code Warm' },
  { file: 'Colorway-ClaudeDark.ovt', name: 'Claude Dark' },
  { file: 'Colorway-Cobalt2.ovt', name: 'Cobalt2' },
  { file: 'Colorway-Cursor.ovt', name: 'Cursor' },
  { file: 'Colorway-DarkHorizon.ovt', name: 'Dark Horizon' },
  { file: 'Colorway-DarkMagic.ovt', name: 'Dark Magic' },
  { file: 'Colorway-Dracula.ovt', name: 'Dracula' },
  { file: 'Colorway-DraculaRefined.ovt', name: 'Dracula Refined' },
  { file: 'Colorway-DustyDunes-Darker.ovt', name: 'Dusty Dunes Darker' },
  { file: 'Colorway-DustyDunes.ovt', name: 'Dusty Dunes' },
  { file: 'Colorway-EarthBound-Darker.ovt', name: 'Earthbound Darker' },
  { file: 'Colorway-EarthBound.ovt', name: 'Earthbound' },
  { file: 'Colorway-EtherealDefault.ovt', name: 'Ethereal Default' },
  { file: 'Colorway-EtherealFallenAngel.ovt', name: 'Ethereal Fallen Angel' },
  { file: 'Colorway-EtherealFrutiger.ovt', name: 'Ethereal Frutiger' },
  { file: 'Colorway-EtherealGothicAngel.ovt', name: 'Ethereal Gothic Angel' },
  { file: 'Colorway-EtherealKerubin.ovt', name: 'Ethereal Kerubin' },
  { file: 'Colorway-EtherealLuminousSpace.ovt', name: 'Ethereal Luminous Space' },
  { file: 'Colorway-EtherealWindows7.ovt', name: 'Ethereal Windows 7' },
  { file: 'Colorway-EtherealY2KAero.ovt', name: 'Ethereal Y2K Aero' },
  { file: 'Colorway-Everforest-Hard.ovt', name: 'Everforest Dark Hard' },
  { file: 'Colorway-Everforest-Light-Hard.ovt', name: 'Everforest Light Hard' },
  { file: 'Colorway-Everforest-Light-Soft.ovt', name: 'Everforest Light Soft' },
  { file: 'Colorway-Everforest-Light.ovt', name: 'Everforest Light' },
  { file: 'Colorway-Everforest-Soft.ovt', name: 'Everforest Dark Soft' },
  { file: 'Colorway-EvondevDracula-Author.ovt', name: 'Evondev Author Contrast' },
  { file: 'Colorway-EvondevDracula-New.ovt', name: 'Evondev New Contrast' },
  { file: 'Colorway-EvondevDracula-Night.ovt', name: 'Evondev Night Contrast' },
  { file: 'Colorway-EvondevDracula.ovt', name: 'Evondev Dracula' },
  { file: 'Colorway-Fairyfloss.ovt', name: 'Fairyfloss' },
  { file: 'Colorway-FireSpring-Darker.ovt', name: 'Fire Spring Darker' },
  { file: 'Colorway-FireSpring.ovt', name: 'Fire Spring' },
  { file: 'Colorway-Flexoki.ovt', name: 'Flexoki' },
  { file: 'Colorway-FluffyDark.ovt', name: 'Fluffy Dark' },
  { file: 'Colorway-GitHub.ovt', name: 'GitHub' },
  { file: 'Colorway-Gruvbox.ovt', name: 'Gruvbox' },
{ file: 'Colorway-HatsuneMiku.ovt', name: 'Hatsune Miku' },
  { file: 'Colorway-Kanagawa.ovt', name: 'Kanagawa' },
  { file: 'Colorway-KickDark.ovt', name: 'Kick Dark' },
  { file: 'Colorway-Kawaii.ovt', name: 'Kawaii' },
  { file: 'Colorway-LoFiGreenDark.ovt', name: 'Lo-Fi Green Dark' },
  { file: 'Colorway-LucentOrng.ovt', name: 'Lucent Orng' },
  { file: 'Colorway-Macaroon.ovt', name: 'Pink Glaze Macaroon' },
  { file: 'Colorway-Magicant.ovt', name: 'Magicant' },
  { file: 'Colorway-Material.ovt', name: 'Material' },
  { file: 'Colorway-InkCrimson.ovt', name: 'Ink Crimson' },
  { file: 'Colorway-Matrix.ovt', name: 'Matrix' },
  { file: 'Colorway-Mercury.ovt', name: 'Mercury' },
  { file: 'Colorway-MikuBetter.ovt', name: 'Miku Better' },
  { file: 'Colorway-ModernPurple.ovt', name: 'Modern Purple' },
  { file: 'Colorway-Monokai.ovt', name: 'Monokai' },
  { file: 'Colorway-Moonside.ovt', name: 'Moonside' },
  { file: 'Colorway-NightOwl.ovt', name: 'Night Owl' },
  { file: 'Colorway-Nord.ovt', name: 'Nord' },
  { file: 'Colorway-OC2.ovt', name: 'OC-2' },
  { file: 'Colorway-OneDark.ovt', name: 'One Dark' },
  { file: 'Colorway-OneDarkPro.ovt', name: 'One Dark Pro' },
  { file: 'Colorway-OpenCode.ovt', name: 'OpenCode' },
  { file: 'Colorway-Orng.ovt', name: 'Orng' },
  { file: 'Colorway-OsakaJade.ovt', name: 'Osaka Jade' },
{ file: 'Colorway-Palenight.ovt', name: 'Palenight' },
   { file: 'Colorway-PastelPixels.ovt', name: 'Pastel Pixels' },
   { file: 'Colorway-RosePine-Foam.ovt', name: 'Rosé Pine — Foam' },
  { file: 'Colorway-RosePine-Gold.ovt', name: 'Rosé Pine — Gold' },
  { file: 'Colorway-RosePine-Iris.ovt', name: 'Rosé Pine — Iris' },
  { file: 'Colorway-RosePine-Love.ovt', name: 'Rosé Pine — Love' },
  { file: 'Colorway-RosePine-Pine.ovt', name: 'Rosé Pine — Pine' },
  { file: 'Colorway-RosePine-Rose.ovt', name: 'Rosé Pine — Rose' },
  { file: 'Colorway-RosePineDawn-Foam.ovt', name: 'Rose Pine Dawn — Foam' },
  { file: 'Colorway-RosePineDawn-Gold.ovt', name: 'Rose Pine Dawn — Gold' },
  { file: 'Colorway-RosePineDawn-Iris.ovt', name: 'Rose Pine Dawn — Iris' },
  { file: 'Colorway-RosePineDawn-Love.ovt', name: 'Rose Pine Dawn — Love' },
  { file: 'Colorway-RosePineDawn-Pine.ovt', name: 'Rose Pine Dawn — Pine' },
  { file: 'Colorway-RosePineDawn-Rose.ovt', name: 'Rosé Pine Dawn — Rose' },
  { file: 'Colorway-RosePineMoon-Foam.ovt', name: 'Rosé Pine Moon — Foam' },
  { file: 'Colorway-RosePineMoon-Gold.ovt', name: 'Rosé Pine Moon — Gold' },
  { file: 'Colorway-RosePineMoon-Iris.ovt', name: 'Rosé Pine Moon — Iris' },
  { file: 'Colorway-RosePineMoon-Love.ovt', name: 'Rosé Pine Moon — Love' },
  { file: 'Colorway-RosePineMoon-Pine.ovt', name: 'Rosé Pine Moon — Pine' },
  { file: 'Colorway-RosePineMoon-Rose.ovt', name: 'Rosé Pine Moon — Rose' },
  { file: 'Colorway-ShadesofPurple.ovt', name: 'Shades of Purple' },
{ file: 'Colorway-SolarizedDark.ovt', name: 'Solarized Dark+' },
   { file: 'Colorway-SLSO8Pixels.ovt', name: 'SLSO8 Pixels' },
   { file: 'Colorway-SolarizedLight.ovt', name: 'Solarized Light+' },
  { file: 'Colorway-SpiritedAway.ovt', name: 'Spirited Away' },
  { file: 'Colorway-Synthwave84.ovt', name: 'Synthwave 84' },
{ file: 'Colorway-Tokyonight.ovt', name: 'Tokyonight' },
   { file: 'Colorway-TwitchDark.ovt', name: 'Twitch Dark' },
   { file: 'Colorway-YouTubeDark.ovt', name: 'YouTube Dark' },
   { file: 'Colorway-Vercel.ovt', name: 'Vercel' },
  { file: 'Colorway-Vesper.ovt', name: 'Vesper' },
  { file: 'Colorway-Zenburn.ovt', name: 'Zenburn' },
  { file: 'Colorway-ZombieThreed-Darker.ovt', name: 'Zombie Threed Darker' },
  { file: 'Colorway-ZombieThreed.ovt', name: 'Zombie Threed' },
  { file: 'Colorway-matchalk.ovt', name: 'matchalk' },
];

export const PATTERNS = [
  { file: 'pattern.svg', name: 'Diagonal' },
  { file: 'bamboo.svg', name: 'Bamboo' },
  { file: 'bank-note.svg', name: 'Bank Note' },
  { file: 'charlie-brown.svg', name: 'Charlie Brown' },
  { file: 'diagonal-lines.svg', name: 'Diagonal Lines' },
  { file: 'formal-invitation.svg', name: 'Formal Invitation' },
  { file: 'heavy-rain.svg', name: 'Heavy Rain' },
  { file: 'morphing-diamonds.svg', name: 'Morphing Diamonds' },
  { file: 'parkay-floor.svg', name: 'Parkay Floor' },
  { file: 'pixel-dots.svg', name: 'Pixel Dots' },
  { file: 'rails.svg', name: 'Rails' },
  { file: 'rain.svg', name: 'Rain' },
  { file: 'tiny-checkers.svg', name: 'Tiny Checkers' },
  { file: 'zig-zag.svg', name: 'Zig Zag' },
];

export const DEFAULT_PATTERN = 'pattern.svg';
