export const THEMES = [
  { file: 'Colorway-90sAnime.ovt', name: '90s Anime' },
  { file: 'Colorway-AMOLED.ovt', name: 'AMOLED' },
  { file: 'Colorway-AdaptaEvergreen.ovt', name: 'Adapta Evergreen' },
  { file: 'Colorway-Aura.ovt', name: 'Aura' },
  { file: 'Colorway-Ayu.ovt', name: 'Ayu' },
  { file: 'Colorway-Carbonfox.ovt', name: 'Carbonfox' },
  { file: 'Colorway-CatppuccinFrappe-Blue.ovt', name: 'Catppuccin Frappé – Blue' },
  { file: 'Colorway-CatppuccinFrappe-Green.ovt', name: 'Catppuccin Frappé – Green' },
  { file: 'Colorway-CatppuccinFrappe-Lavender.ovt', name: 'Catppuccin Frappé – Lavender' },
  { file: 'Colorway-CatppuccinFrappe-Maroon.ovt', name: 'Catppuccin Frappé – Maroon' },
  { file: 'Colorway-CatppuccinFrappe-Peach.ovt', name: 'Catppuccin Frappé – Peach' },
  { file: 'Colorway-CatppuccinFrappe-Pink.ovt', name: 'Catppuccin Frappé – Pink' },
  { file: 'Colorway-CatppuccinFrappe-Red.ovt', name: 'Catppuccin Frappé – Red' },
  { file: 'Colorway-CatppuccinFrappe-Rosewater.ovt', name: 'Catppuccin Frappé – Rosewater' },
  { file: 'Colorway-CatppuccinFrappe-Teal.ovt', name: 'Catppuccin Frappé – Teal' },
  { file: 'Colorway-CatppuccinFrappe-Yellow.ovt', name: 'Catppuccin Frappé – Yellow' },
  { file: 'Colorway-CatppuccinLatte-Blue.ovt', name: 'Catppuccin Latte – Blue' },
  { file: 'Colorway-CatppuccinLatte-Green.ovt', name: 'Catppuccin Latte – Green' },
  { file: 'Colorway-CatppuccinLatte-Lavender.ovt', name: 'Catppuccin Latte – Lavender' },
  { file: 'Colorway-CatppuccinLatte-Maroon.ovt', name: 'Catppuccin Latte – Maroon' },
  { file: 'Colorway-CatppuccinLatte-Peach.ovt', name: 'Catppuccin Latte – Peach' },
  { file: 'Colorway-CatppuccinLatte-Pink.ovt', name: 'Catppuccin Latte – Pink' },
  { file: 'Colorway-CatppuccinLatte-Red.ovt', name: 'Catppuccin Latte – Red' },
  { file: 'Colorway-CatppuccinLatte-Rosewater.ovt', name: 'Catppuccin Latte – Rosewater' },
  { file: 'Colorway-CatppuccinLatte-Teal.ovt', name: 'Catppuccin Latte – Teal' },
  { file: 'Colorway-CatppuccinLatte-Yellow.ovt', name: 'Catppuccin Latte – Yellow' },
  { file: 'Colorway-CatppuccinMacchiato-Blue.ovt', name: 'Catppuccin Macchiato – Blue' },
  { file: 'Colorway-CatppuccinMacchiato-Green.ovt', name: 'Catppuccin Macchiato – Green' },
  { file: 'Colorway-CatppuccinMacchiato-Lavender.ovt', name: 'Catppuccin Macchiato – Lavender' },
  { file: 'Colorway-CatppuccinMacchiato-Maroon.ovt', name: 'Catppuccin Macchiato – Maroon' },
  { file: 'Colorway-CatppuccinMacchiato-Peach.ovt', name: 'Catppuccin Macchiato – Peach' },
  { file: 'Colorway-CatppuccinMacchiato-Pink.ovt', name: 'Catppuccin Macchiato – Pink' },
  { file: 'Colorway-CatppuccinMacchiato-Red.ovt', name: 'Catppuccin Macchiato – Red' },
  { file: 'Colorway-CatppuccinMacchiato-Rosewater.ovt', name: 'Catppuccin Macchiato – Rosewater' },
  { file: 'Colorway-CatppuccinMacchiato-Teal.ovt', name: 'Catppuccin Macchiato – Teal' },
  { file: 'Colorway-CatppuccinMacchiato-Yellow.ovt', name: 'Catppuccin Macchiato – Yellow' },
  { file: 'Colorway-CatppuccinMocha.ovt', name: 'Catppuccin Mocha (default)' },
  { file: 'Colorway-Cobalt2.ovt', name: 'Cobalt2' },
  { file: 'Colorway-Dracula.ovt', name: 'Dracula' },
  { file: 'Colorway-Flexoki.ovt', name: 'Flexoki' },
  { file: 'Colorway-GitHub.ovt', name: 'GitHub' },
  { file: 'Colorway-Gruvbox.ovt', name: 'Gruvbox' },
  { file: 'Colorway-Kanagawa.ovt', name: 'Kanagawa' },
  { file: 'Colorway-Matrix.ovt', name: 'Matrix' },
  { file: 'Colorway-Nord.ovt', name: 'Nord' },
  { file: 'Colorway-OpenCode.ovt', name: 'Open Code' },
  { file: 'Colorway-RosePine-Foam.ovt', name: 'Rosé Pine – Foam' },
  { file: 'Colorway-RosePine-Gold.ovt', name: 'Rosé Pine – Gold' },
  { file: 'Colorway-SolarizedDark.ovt', name: 'Solarized Dark' },
  { file: 'Colorway-SolarizedLight.ovt', name: 'Solarized Light' },
  { file: 'Colorway-Synthwave84.ovt', name: 'Synthwave 84' },
  { file: 'Colorway-Tokyonight.ovt', name: 'Tokyo Night' },
  { file: 'Colorway-Vercel.ovt', name: 'Vercel' },
  { file: 'Colorway-Zenburn.ovt', name: 'Zenburn' },
];
